name: ToDoList CI/CD

on: 
  push:
    branches:
      - dev

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install missing dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff2dec1 \
            libvpx6 \
            libevent-2.1-7 \
            libopus0 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer1.0-0 \
            libflite1 \
            libavif13 \
            libharfbuzz-icu0 \
            libhyphen0 \
            libmanette0 \
            libgles2-mesa \
            libx264-155

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          playwright install  

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
          DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
          PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_DISCOVERY_URL: ${{ secrets.GOOGLE_DISCOVERY_URL }}
        run: |
          pytest --cov=app --tb=short --disable-warnings
